### ISSUE TITLE
Interface requires Jenkins layer

### ISSUE THREAD

**Issue by hloeung** [freeekanayaka/interface-jenkins-slave#1]
Hi,

I'm trying to rewrite the jenkins-slave charm using the reactive framework.

When trying to use just the jenkins-slave interface, it fails as it needs charms.layer.jenkins for 'credentials' and 'api', see https://github.com/freeekanayaka/interface-jenkins-slave/blob/master/requires.py#L16.

When trying to use the jenkins layer, it tries to install and configure up Jenkins.

Any chance we could fix this so the interface doesn't rely on the Jenkins layer and can be reused in other charms to talk to a Jenkins master without trying to configure up Jenkins itself?

**Comment by hloeung** [comment]
https://github.com/jenkinsci/jenkins-charm/issues/54

**Comment by hloeung** [comment]
Maybe I'm misunderstanding how layers and interfaces works. Perhaps that's the bit that supposed to be implemented in provides.py?

**Comment by freeekanayaka** [comment]
@hloeung yes, I think there's some misunderstanding, you shouldn't be using layer:jenkins in the slave, but rather just interface:jenkins-slave, implementing the requires.py part. It's been a very long time since I did anything with reactive and charms, so please take that with a grain of salt and check the reactive documentation.

**Comment by hloeung** [comment]
@freeekanayaka gotcha. I don't have much experience with implementing interfaces so for now am just using @hooks()

Thanks.
